sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service_account.json.enc -out service_account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-accound --key-file service_account.json
  - gcloud config set project tikitakaenv
  - gcloud config compute/zone us-west2-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t armangurkan1/react-test1 -f ./client/Dockerfile.dev
script:
  - docker run -e CI=true USERNAME/docker-react npm run test

deploy: :
  provider: script
  script: bash ./deploy.sh
  on:
     branch: tikitakaEnvR
