sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service_account.json.enc -out service_account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOme/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-accound --key-file service-account.json
